// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ptf-mono/DeepBlack.tsx": () => import("../components/mockups/ptf-mono/DeepBlack.tsx"),
  "./components/mockups/ptf-mono/PureWhite.tsx": () => import("../components/mockups/ptf-mono/PureWhite.tsx"),
  "./components/mockups/ptf-mono/WarmInk.tsx": () => import("../components/mockups/ptf-mono/WarmInk.tsx")
};
